<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OcupacionGiroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ocupaciones = [
            'Acabado de hilos',
            'Acabado de telas',
            'Actividades de clubes deportivos profesionales',
            'Administración de caminos puentes y servicios auxiliares',
            'Administración de centrales camioneras y servicios auxiliares',
            'Administración de inmuebles',
            'Administración de puertos marítimos lacustres y fluviales',
            'Administradoras de tarjeta de crédito',
            'Adquisición de vivienda residencial',
            'Adquisición de vivienda tipo medio',
            'Aeropuerto civil',
            'Agencia aduanal',
            'Agencia de ferrocarril',
            'Agencia de inhumaciones',
            'Agencia de mudanzas',
            'Agencia de publicidad',
            'Agencia de turismo',
            'Agencia de vapores y buques',
            'Agencia noticiosa',
            'Agencias de rifas y sorteos (quinielas y loteria)',
            'Agente de bolsa',
            'Agente de seguros',
            'Agricultor',
            'Agrupaciones mercantiles, profesionales, cívicas, políticas, laborales y religiosas',
            'Almacenes de deposito nacionales',
            'Almacenes de deposito privados',
            'Alquiler de equipos electrónicos',
            'Alquiler de lanchas y veleros',
            'Alquiler de mobiliario y equipo para comercios servicios y oficinas',
            'Alquiler de ropa',
            'Alquiler de sillas y vajillas para banquetes',
            'Alquiler de terrenos locales y edificios no residenciales',
            'Alquiler o renta de automoviles sin chofer',
            'Arrendadoras financieras nacionales',
            'Arrendadoras financieras privadas',
            'Arrendamiento de equipo para procesamiento electrónico de datos',
            'Arrendamiento de inmuebles residenciales',
            'Arrendamiento de maquinaria',
            'Aserradero',
            'Asociaciones y confederaciones',
            'Autotransporte de carga de productos específicos',
            'Autotransporte de materiales de construcción',
            'Autotransporte escolar turístico en autobús y otros especializados excepto ambulancias',
            'Baños',
            'Barbería y peluquería',
            'Bares y cantinas',
            'Beneficio de arroz excepto molienda',
            'Beneficio de café excepto molienda y tostado',
            'Beneficio de lanas',
            'Beneficio de maderas (desflemado estufado cepillado etc)',
            'Beneficio de otras fibras textiles',
            'Beneficio de pelo y cerda para la industria textil',
            'Bolsa de valores',
            'Cafetería',
            'Caja de ahorros',
            'Cámaras de comercio',
            'Cámaras industriales',
            'Campos de turismo',
            'Captación, tratamiento, conducción y distribución de agua potable excepto de riego',
            'Captación, tratamiento, conducción y distribución de agua potable excepto de riego',
            'Captura de atún bonito barrilete y similares',
            'Captura de camarón',
            'Captura de crustáceos moluscos reptiles anfibios y otra fauna de agua dulce',
            'Captura de mamíferos anfibios y diversos invertebrados de mar',
            'Captura de ostión',
            'Captura de otros crustáceos y moluscos marinos',
            'Captura de otros peces en estuarios costas o alta mar',
            'Captura de peces en ríos lagos y estuarios',
            'Captura de sardina y similares',
            'Captura de tiburón cazón raya y similares',
            'Captura de tortuga y otros reptiles marinos',
            'Captura y preservación de especies animales salvajes',
            'Carga y estiba portuaria',
            'Casa de cambio',
            'Casa de huéspedes',
            'Casas de bolsa nacionales',
            'Casas de bolsa privadas',
            'Caza',
            'Centro de beneficencia',
            'Centro deportivo',
            'Centro nocturno',
            'Cervecería',
            'Club social',
            'Colocacion de duelas parquet lambrines y otros trabajos de carpinteria',
            'Comisionista',
            'Compañias de fianzas nacionales',
            'Compañias de fianzas privadas',
            'Compañias de seguros nacionales',
            'Compañias de seguros privadas',
            'Compra de articulos sanitarios',
            'Compraventa de accesorios para muebles',
            'Compraventa de algodon',
            'Compraventa de alimento para ganado',
            'Compraventa de alimentos para aves y otros animales',
            'Compraventa de alimentos, bebidas y productos de tabaco',
            'Compraventa de anilinas',
            'Compraventa de antigüedades',
            'Compraventa de aparatos cientificos y de precision',
            'Compraventa de armas de fuego',
            'Compraventa de articulos de boneteria',
            'Compraventa de articulos de cristal loza y porcelana',
            'Compraventa de articulos de ferreteria',
            'Compraventa de articulos de lenceria',
            'Compraventa de articulos de merceria y cederia',
            'Compraventa de artículos de óptica',
            'Compraventa de artículos de peletería',
            'Compraventa de artículos de plata',
            'Compraventa de artículos de talabartería',
            'Compraventa de artículos de tlapalería',
            'Compraventa de artículos de yute y henequén',
            'Compraventa de artículos fotográficos y cinematográficos',
            'Compraventa de artículos médicos',
            'Compraventa de artículos no clasificados en otra parte',
            'Compraventa de artículos para decoración',
            'Compraventa de artículos para deporte',
            'Compraventa de artículos para el hogar (electrodomésticos, refacciones, loza y porcelana, antigüedades)',
            'Compraventa de artículos para la explotación de minas',
            'Compraventa de artículos para regalo',
            'Compraventa de artículos regionales curiosidades y artesanías',
            'Compraventa de artículos religiosos',
            'Compraventa de artículos y aparatos ortopédicos',
            'Compraventa de automóviles y camiones nuevos',
            'Compraventa de automóviles y camiones usados',
            'Compraventa de aves en pie',
            'Compraventa de azúcar',
            'Compraventa de basculas balanzas y aparatos similares para equipo pesado',
            'Compraventa de bicicletas y sus accesorios',
            'Compraventa de bienes inmuebles y artículos diversos',
            'Compraventa de calzado',
            'Compraventa de carbón y otros combustibles',
            'Compraventa de carne de aves',
            'Compraventa de carne de res y otras especies de ganado',
            'Compraventa de casas y otros inmuebles',
            'Compraventa de casimires',
            'Compraventa de cemento cal yeso y otros productos a base de minerales no metálicos',
            'Compraventa de ceras y parafinas',
            'Compraventa de cerveza',
            'Compraventa de chile seco y especias',
            'Compraventa de colorantes para la industria',
            'Compraventa de costales y bolsas',
            'Compraventa de cueros y pieles sin curtir',
            'Compraventa de desperdicios de papel',
            'Compraventa de desperdicios industriales',
            'Compraventa de diamantes',
            'Compraventa de discos y cassettes',
            'Compraventa de dulces',
            'Compraventa de equipo contra incendio',
            'Compraventa de equipo de procesamiento electrónico de datos',
            'Compraventa de equipo de trabajo y protección industrial',
            'Compraventa de equipo de transporte, sus refacciones y accesorios',
            'Compraventa de equipo y mobiliario para hoteles restaurantes billares boliches peluquerías y salones de belleza',
            'Compraventa de equipos de refrigeración comercial',
            'Compraventa de equipos químicos y para laboratorio',
            'Compraventa de equipos y aparatos de aire acondicionado',
            'Compraventa de especias y artículos alimenticios deshidratados',
            'Compraventa de fertilizantes y plaguicidas',
            'Compraventa de fierro laminado y en lingotes',
            'Compraventa de fierro usado',
            'Compraventa de flores y adornos florales artificiales',
            'Compraventa de flores y adornos florales naturales',
            'Compraventa de fluidos y gases',
            'Compraventa de forrajes en estado natural',
            'Compraventa de frutas',
            'Compraventa de ganado mayor en pie',
            'Compraventa de ganado menor en pie',
            'Compraventa de gas para uso domestico o comercial',
            'Compraventa de gases, combustibles y lubricantes',
            'Compraventa de gasolina y diesel',
            'Compraventa de henequén e ixtle',
            'Compraventa de huevo',
            'Compraventa de instrumentos y artículos musicales',
            'Compraventa de jarcieria reatas canastas y artículos tejidos de fibra',
            'Compraventa de juguetes',
            'Compraventa de lana',
            'Compraventa de leche',
            'Compraventa de legumbres y hortalizas',
            'Compraventa de libros',
            'Compraventa de llantas',
            'Compraventa de lubricantes',
            'Compraventa de madera',
            'Compraventa de manteca',
            'Compraventa de maquinaria equipo e implementos para la agricultura y la ganadería',
            'Compraventa de maquinaria equipo implementos y herramientas para trabajar la madera metales y otros materiales',
            'Compraventa de maquinaria nueva',
            'Compraventa de maquinaria usada',
            'Compraventa de maquinaria, equipo, instrumentos, aparatos y herramientas, sus refacciones y accesorios',
            'Compraventa de maquinas de coser y tejedoras',
            'Compraventa de maquinas de escribir',
            'Compraventa de material para instalaciones eléctricas y de sonido',
            'Compraventa de materiales para construcción',
            'Compraventa de materias primas animales',
            'Compraventa de materias primas de origen mineral',
            'Compraventa de materias primas, materiales y auxiliares (algodón, cemento, sanitarios, pieles, ferretería, madera, pinturas)',
            'Compraventa de medicinas',
            'Compraventa de motocicletas y sus accesorios',
            'Compraventa de muebles',
            'Compraventa de muebles para consultorios y sanatorios',
            'Compraventa de muebles y artículos para oficina',
            'Compraventa de otras fibras comerciales',
            'Compraventa de otras joyas',
            'Compraventa de otras materias primas de origen animal',
            'Compraventa de otras materias primas vegetales',
            'Compraventa de otros aparatos eléctricos',
            'Compraventa de otros aparatos eléctricos y electrónicos de uso domestico',
            'Compraventa de otros artículos de piel',
            'Compraventa de otros artículos de plástico',
            'Compraventa de otros artículos para el hogar',
            'Compraventa de otros metales y minerales laminados y en lingotes',
            'Compraventa de otros productos alimenticios agrícolas en estado natural',
            'Compraventa de otros productos de hule',
            'Compraventa de otros productos lácteos',
            'Compraventa de otros productos textiles',
            'Compraventa de pan y pasteles',
            'Compraventa de papelería y artículos de escritorio',
            'Compraventa de paraguas sombrillas ropa usada y otros artículos de uso personal',
            'Compraventa de partes y refacciones para vehículos aéreos',
            'Compraventa de perfumes',
            'Compraventa de pescados y mariscos',
            'Compraventa de petroleo combustible',
            'Compraventa de pieles finas con pelo',
            'Compraventa de pinturas barnices y brochas',
            'Compraventa de prendas de vestir y otros artículos de uso personal',
            'Compraventa de productos veterinarios y otros artículos para el cuidado de los animales',
            'Compraventa de pulque',
            'Compraventa de refacciones para aparatos eléctricos',
            'Compraventa de refacciones para maquinaria',
            'Compraventa de refacciones y accesorios de maquinas aparatos e instrumentos para el hogar excepto, los de maquinas de coser y tejer',
            'Compraventa de refacciones y accesorios nuevos para autos y camiones',
            'Compraventa de refacciones y accesorios usados para automóviles y camiones',
            'Compraventa de refrescos aguas gaseosas y aguas purificadas',
            'Compraventa de refrigeradores lavadoras y estufas',
            'Compraventa de relojes',
            'Compraventa de ropa',
            'Compraventa de sal',
            'Compraventa de semillas para siembra',
            'Compraventa de semillas y granos',
            'Compraventa de sillas de montar',
            'Compraventa de sombreros',
            'Compraventa de substancias químicas para la industria',
            'Compraventa de tabaco',
            'Compraventa de tabacos puros y cigarros',
            'Compraventa de tapetes y alfombras',
            'Compraventa de tapices',
            'Compraventa de telas',
            'Compraventa de televisores consolas radios modulares y tocacintas',
            'Compraventa de terrenos',
            'Compraventa de vehículos acuáticos y sus refacciones',
            'Compraventa de vehículos aéreos',
            'Compraventa de velas y veladoras',
            'Compraventa de vidrios cristales y emplomados',
            'Compraventa de vinos y licores',
            'Compraventa de vísceras de ganado crudas y semicrudas',
            'Compraventa en tiendas de autoservicio y de departamentos especializados por línea de mercancías',
            'Compresora de algodón',
            'Comunicaciones',
            'Congeladora de productos marinos',
            'Construcción de casas y techos desarmables',
            'Construcción de edificios industriales y para fines análogos',
            'Construcción de edificios para oficinas escuelas hospitales hoteles y otros no residenciales',
            'Construcción de estadios monumentos y otras obras de ingeniería',
            'Construcción de inmuebles',
            'Construcción de pistas de aterrizaje ductos y otras obras vinculadas a las vías de comunicación',
            'Construcción de presas',
            'Construcción de puertos',
            'Construcción de vías de comunicación',
            'Construcción de vivienda residencial',
            'Construcción de vivienda tipo medio',
            'Construcción e instalación de lineas telefónicas torres emisoras de radio y televisión y otras obras conexas',
            'Construcción e instalación de plantas generadoras y lineas de transmisión y distribución de energía eléctrica',
            'Construcción, reconstrucción y ensamble de equipo de transporte y sus partes',
            'Consulado',
            'Consumos personales',
            'Contratación de obras completas de construcción (casas, departamentos, inmuebles, pavimentación, no residenciales, vías de comunicación)',
            'Corresponsal bancario',
            'créditos para Adquisición de bienes de consumo duradero',
            'Cria de ganado caballar',
            'Cria de ganado de lidia',
            'Cria de otros equinos y ganado para el trabajo',
            'Cria y explotación de abejas',
            'Cria y explotación de animales domésticos, para laboratorio y otros fines no alimenticios',
            'Cria y explotación de conejos y liebres',
            'Cria y explotación de gallina para producción de huevo',
            'Cria y explotación de ganado caprino',
            'Cria y explotación de ganado ovino',
            'Cria y explotación de ganado porcino',
            'Cria y explotación de ganado vacuno para carne',
            'Cria y explotación de ganado vacuno para leche',
            'Cria y explotación de gusano de seda',
            'Cria y explotación de ostras',
            'Cria y explotación de otras aves para alimentación',
            'Cria y explotación de peces otras especies animales y plantas acuáticas',
            'Cria y explotación de pollos',
            'Cultivo de agave o mezcal',
            'Cultivo de aguacate',
            'Cultivo de ajo',
            'Cultivo de ajonjolí',
            'Cultivo de alfalfa',
            'Cultivo de algodón',
            'Cultivo de alpiste',
            'Cultivo de arroz',
            'Cultivo de avena',
            'Cultivo de cacahuate',
            'Cultivo de cacao',
            'Cultivo de café',
            'Cultivo de calabaza',
            'Cultivo de camote',
            'Cultivo de caña de azúcar',
            'Cultivo de cartamo',
            'Cultivo de cebada',
            'Cultivo de cebolla',
            'Cultivo de chile',
            'Cultivo de copra',
            'Cultivo de durazno',
            'Cultivo de esparrago',
            'Cultivo de especias',
            'Cultivo de flores y plantas de ornato',
            'Cultivo de fresa',
            'Cultivo de frijol',
            'Cultivo de garbanzo',
            'Cultivo de guayaba',
            'Cultivo de henequén',
            'Cultivo de jitomate',
            'Cultivo de lenteja',
            'Cultivo de limón',
            'Cultivo de linaza',
            'Cultivo de lino',
            'Cultivo de maguey',
            'Cultivo de maíz',
            'Cultivo de mango',
            'Cultivo de manzana',
            'Cultivo de melón',
            'Cultivo de milo',
            'Cultivo de naranja',
            'Cultivo de nopal',
            'Cultivo de nuez',
            'Cultivo de olivo',
            'Cultivo de otras fibras duras',
            'Cultivo de otras hortalizas',
            'Cultivo de otras semillas',
            'Cultivo de otros arboles frutales',
            'Cultivo de papa',
            'Cultivo de papaya',
            'Cultivo de piña',
            'Cultivo de plátano',
            'Cultivo de remolacha',
            'Cultivo de sandia',
            'Cultivo de semillas mejoradas',
            'Cultivo de sorgo',
            'Cultivo de soya',
            'Cultivo de tabaco',
            'Cultivo de tamarindo',
            'Cultivo de tomate',
            'Cultivo de toronja',
            'Cultivo de trigo',
            'Cultivo de vainilla',
            'Cultivo de vid',
            'Cultivo de yuca',
            'Cultivo y explotación de palma y lechuguilla',
            'Curtidora',
            'Decoración en general',
            'Demolición de inmuebles',
            'Departamento del df',
            'Desarrolladores de vivienda',
            'Descascarado y tostado de cacahuate y nuez',
            'Descascaradora y tostadora de semilla de calabaza',
            'Desecado de tabaco',
            'Desfibracion de algodón',
            'Desfibracion de henequén',
            'Deshidratacion de frutas',
            'Deshidratacion de plantas para forrajes',
            'Despacho de otros profesionistas',
            'Despepite de algodón',
            'Destilación de alcohol etílico',
            'Distribución de energía eléctrica',
            'Distribución de otros productos químicos farmacéuticos',
            'Distribución y alquiler de películas',
            'Distribución y compraventa de periódicos y revistas',
            'Edición de libros',
            'Edición de periódicos y revistas',
            'Elaboración de objetos artísticos de alfarería y cerámica',
            'Elaboración de pulque',
            'Embotellado de aguas minerales',
            'Empacadora de carne',
            'Empacadora de conservas alimenticias',
            'Empacadora de especias',
            'Empacadora de frutas y legumbres',
            'Empacadora de otros mariscos',
            'Empacadora de pescado',
            'Empacadora de te',
            'Empleado del sector privado (u.i.f)',
            'Empleado del sector publico (u.i.f)',
            'Empresa de servicio de limpieza',
            'Empresa de teléfonos',
            'Empresa de telégrafos',
            'Empresas controladoras financieras',
            'Empresas controladoras no financieras',
            'Empresas de auto financiamiento automotriz',
            'Empresas de auto financiamiento residencial',
            'Empresas de seguridad privada',
            'Empresas transportadoras de valores',
            'Encuadernacion',
            'Establecimientos privados de instrucción educación cultura e investigación',
            'Establecimientos públicos de instrucción educación subprofesional y profesional cultura e investigación',
            'Estacionamiento privado para vehículos',
            'Estacionamiento publico para vehículos',
            'Estadios y arenas',
            'Estudiante, desempleado, jubilado, pensionado, discapacitado (u.i.f)',
            'Estudio fotográfico',
            'Estudios cinematográficos',
            'Exploración de petroleo por compañías',
            'Explotación de barbasco arborescentes y arbustos',
            'Explotación de candelilla',
            'Explotación de hule',
            'Explotación de raíces',
            'Explotación de sal',
            'Explotación de sal marina y de yacimientos',
            'Extracción de alquitrán vegetal',
            'Extracción de carbón vegetal',
            'Extracción de chicle',
            'Extracción de colofonia',
            'Extracción de minerales no metálicos, excepto sal',
            'Extracción de otras resinas',
            'Extracción de petroleo crudo y gas natural',
            'Extracción de petróleo crudo y gas natural',
            'Extracción de trementina',
            'Extracción de troncos para aserraderos y para pulpa incluso la madera toscamente aserrada',
            'Extracción de yeso',
            'Extracción y beneficio de arcillas refractarias',
            'Extracción y beneficio de arena y grava',
            'Extracción y beneficio de barita y roca fosfórica',
            'Extracción y beneficio de carbón mineral y grafito',
            'Extracción y beneficio de carbón mineral y grafito',
            'Extracción y beneficio de cobre plomo zinc y otros minerales no ferrosos',
            'Extracción y beneficio de fluorita',
            'Extracción y beneficio de mercurio y antimonio',
            'Extracción y beneficio de mineral de hierro',
            'Extracción y beneficio de minerales metálicos',
            'Extracción y beneficio de oro plata y otros metales preciosos',
            'Extracción y beneficio de otros materiales para construcción',
            'Extracción y beneficio de otros minerales no metálicos excepto sal',
            'Extracción y beneficio de piedra',
            'Extracción y beneficio de sílice',
            'Fabricación de abanicos',
            'Fabricación de abonos y fertilizantes químicos',
            'Fabricación de abrasivos',
            'Fabricación de accesorios para la industria textil',
            'Fabricación de aceites vegetales comestibles',
            'Fabricación de aceites y lubricantes',
            'Fabricación de aceites y mantecas animales comestibles',
            'Fabricación de ácidos industriales',
            'Fabricación de acumuladores',
            'Fabricación de adobe',
            'Fabricación de aguardiente de caña',
            'Fabricación de aguarrás',
            'Fabricación de alambrados y telas de metal',
            'Fabricación de alambre',
            'Fabricación de alfileres agujas y broches',
            'Fabricación de algodón absorbente vendas tela adhesiva y productos similares',
            'Fabricación de algodón esterilizado gasas y vendas',
            'Fabricación de alimento para ganado y otros animales',
            'Fabricación de alimentos',
            'Fabricación de alimentos para aves',
            'Fabricación de almidón',
            'Fabricación de almohadas y cojines',
            'Fabricación de alpargatas babuchas y pantuflas',
            'Fabricación de ampolletas',
            'Fabricación de anilinas',
            'Fabricación de anuncios luminosos',
            'Fabricación de añil',
            'Fabricación de aparatos de intercomunicación',
            'Fabricación de aparatos ozonizadores',
            'Fabricación de aparatos para gimnasia',
            'Fabricación de armas',
            'Fabricación de artículos bordados y deshilados',
            'Fabricación de artículos con hule usado',
            'Fabricación de artículos de baquelita',
            'Fabricación de artículos de carey',
            'Fabricación de artículos de celuloide',
            'Fabricación de artículos de concha',
            'Fabricación de artículos de cuero para viaje',
            'Fabricación de artículos de cuero y hueso',
            'Fabricación de artículos de cuero y piel para zapatero',
            'Fabricación de artículos de joyería',
            'Fabricación de artículos de lona',
            'Fabricación de artículos de palma vara carrizo mimbre y similares',
            'Fabricación de artículos de palma y tule',
            'Fabricación de artículos de peltre',
            'Fabricación de artículos de polietileno',
            'Fabricación de artículos de quincallería y bisutería',
            'Fabricación de artículos para dentista',
            'Fabricación de artículos para escritorio',
            'Fabricación de artículos tejidos de cuero',
            'Fabricación de asbestos y corchos aislantes',
            'Fabricación de ataúdes de madera',
            'Fabricación de ates',
            'Fabricación de azulejos',
            'Fabricación de balones globos y pelotas',
            'Fabricación de bandas y correas de cuero',
            'Fabricación de banderas y adornos de tela',
            'Fabricación de bastones paraguas y sombrillas',
            'Fabricación de bebidas gaseosas',
            'Fabricación de bloques de cemento',
            'Fabricación de bolsas y carteras de cuero',
            'Fabricación de bombas para agua',
            'Fabricación de borras y estopas',
            'Fabricación de botellas',
            'Fabricación de botones de plástico',
            'Fabricación de brochas y pinceles',
            'Fabricación de bujías',
            'Fabricación de butacas de metal',
            'Fabricación de cables de metal',
            'Fabricación de cachuchas y gorras',
            'Fabricación de cajas fuertes',
            'Fabricación de cajas y empaques de madera',
            'Fabricación de cajetas yogurts y otros productos a base de leche',
            'Fabricación de calcetines',
            'Fabricación de calcomanías',
            'Fabricación de calderas tanques y tinacos de metal',
            'Fabricación de calentadores para baño',
            'Fabricación de calzado de cuero o piel',
            'Fabricación de calzado de plástico',
            'Fabricación de calzado e industria del cuero',
            'Fabricación de calzado para deporte excepto de plástico y hule',
            'Fabricación de cámaras fotográficas de cine y proyectores',
            'Fabricación de camisas',
            'Fabricación de candados',
            'Fabricación de candiles y arbotantes',
            'Fabricación de canuteros',
            'Fabricación de carnes frías y embutidos',
            'Fabricación de carriolas y andaderas',
            'Fabricación de carrocerías de metal',
            'Fabricación de carrocerías y redilas de madera',
            'Fabricación de cartón',
            'Fabricación de cartuchos',
            'Fabricación de casimires y paños',
            'Fabricación de casquillos',
            'Fabricación de celuloide y polietileno',
            'Fabricación de cemento',
            'Fabricación de cepillos y plumeros',
            'Fabricación de cera pulimentos y abrillantadores',
            'Fabricación de cercos para calzado',
            'Fabricación de cerillos y fósforos',
            'Fabricación de cerraduras',
            'Fabricación de cerveza',
            'Fabricación de chamarras y abrigos',
            'Fabricación de chocolates',
            'Fabricación de cierres automáticos de metal',
            'Fabricación de cigarros',
            'Fabricación de cintas agujetas y listones',
            'Fabricación de cintas para maquinas calculadoras registradoras y de escribir',
            'Fabricación de clavos cadenas grapas y tachuelas',
            'Fabricación de colas y pegamentos',
            'Fabricación de colchas',
            'Fabricación de colchones y colchonetas',
            'Fabricación de concentrados de frutas',
            'Fabricación de concreto científico',
            'Fabricación de concreto para construcción',
            'Fabricación de conos para nieve',
            'Fabricación de coque y otros derivados del carbón mineral',
            'Fabricación de corbatas',
            'Fabricación de corcholatas',
            'Fabricación de corseteria y ropa interior para dama',
            'Fabricación de cortinas de metal',
            'Fabricación de cortinas de tela y manteleria',
            'Fabricación de costales',
            'Fabricación de crema mantequilla y queso',
            'Fabricación de crisoles',
            'Fabricación de cristales para automóvil',
            'Fabricación de cubiertos y cuchilleria',
            'Fabricación de cubre asientos para vehículos',
            'Fabricación de cuerdas para guitarra',
            'Fabricación de dentífrico',
            'Fabricación de desincrustantes',
            'Fabricación de desinfectantes y desodorizantes',
            'Fabricación de dinamita',
            'Fabricación de discos y cintas para grabaciones',
            'Fabricación de duelas y otros materiales de madera para piso',
            'Fabricación de dulces bombones y confites',
            'Fabricación de emplomados',
            'Fabricación de encajes',
            'Fabricación de encurtidos',
            'Fabricación de engranes de metal',
            'Fabricación de entretelas y fieltros',
            'Fabricación de envases de cartón',
            'Fabricación de envases de lamina',
            'Fabricación de equipo de procesamiento electrónico de datos',
            'Fabricación de equipos para soldar y soldaduras',
            'Fabricación de escobas',
            'Fabricación de esencias',
            'Fabricación de esferas de vidrio',
            'Fabricación de esmeriles',
            'Fabricación de espejos y lunas',
            'Fabricación de espuelas frenos y arneses de metal',
            'Fabricación de estambres',
            'Fabricación de estructuras de metal',
            'Fabricación de estufas',
            'Fabricacion de extinguidores',
            'Fabricacion de fibra de vidrio',
            'Fabricacion de fibras sinteticas',
            'Fabricacion de fierro esponja',
            'Fabricacion de filtros de metal',
            'Fabricacion de flores artificiales',
            'Fabricacion de focos',
            'Fabricacion de formularios y formas continuas',
            'Fabricacion de fornituras militares de cuero',
            'Fabricacion de frituras',
            'Fabricacion de furgones y vagones',
            'Fabricacion de galletas',
            'Fabricacion de gas acetileno',
            'Fabricacion de gasolina y otros productos derivados de la refinacion de petroleo',
            'Fabricacion de gelatinas',
            'Fabricacion de goma de mascar',
            'Fabricacion de grasas y cremas lustradoras',
            'Fabricacion de grenetina',
            'Fabricacion de guantes',
            'Fabricacion de guaraches y sandalias',
            'Fabricacion de harina de pescado',
            'Fabricacion de hebillas de metal',
            'Fabricacion de helados nieves y paletas',
            'Fabricacion de herramientas de metal',
            'Fabricacion de hielo',
            'Fabricacion de hielo seco',
            'Fabricacion de hilados y tejidos de algodon',
            'Fabricacion de hilados y tejidos de fibra de coco',
            'Fabricacion de hilados y tejidos de henequen',
            'Fabricacion de hilados y tejidos de lana',
            'Fabricacion de hilados y tejidos de otras fibras sinteticas',
            'Fabricacion de hilados y tejidos de seda',
            'Fabricacion de hilados y tejidos de yute',
            'Fabricacion de hilos para coser',
            'Fabricacion de hojas para rasurar',
            'Fabricacion de hormas para calzado y tacones',
            'Fabricacion de hule espuma',
            'Fabricacion de impermeabilizantes',
            'Fabricacion de impermeables',
            'Fabricacion de insecticidas y plaguicidas',
            'Fabricacion de jabon y detergente',
            'Fabricacion de jarabes',
            'Fabricacion de jaulas de metal',
            'Fabricacion de juguetes excepto los de hule y de plastico moldeados',
            'Fabricacion de juntas y empaques de corcho',
            'Fabricacion de ladrillos',
            'Fabricacion de laminas de hierro y acero',
            'Fabricacion de laminas perfiles tubos y otros materiales similares de plastico',
            'Fabricacion de lamparas electricas',
            'Fabricacion de lanolina',
            'Fabricacion de lapices',
            'Fabricacion de leche condensada evaporada y pulverizada',
            'Fabricacion de levaduras',
            'Fabricacion de libretas cuadernos y hojas para encuadernacion',
            'Fabricacion de lija',
            'Fabricacion de linoleo',
            'Fabricacion de llantas y camaras para vehiculos',
            'Fabricacion de lona',
            'Fabricacion de loza y porcelana',
            'Fabricacion de malta',
            'Fabricacion de mangos de madera',
            'Fabricacion de mantecas vegetales comestibles',
            'Fabricacion de mantones y chalinas',
            'Fabricacion de maquinaria e implementos agricolas',
            'Fabricacion de maquinas calculadoras registradoras y de escribir',
            'Fabricacion de maquinas de coser',
            'Fabricacion de marcos y molduras de madera',
            'Fabricacion de marquetas y estuchados de azucar',
            'Fabricacion de material fotografico',
            'Fabricacion de material para instalaciones electricas',
            'Fabricacion de materiales asfalticos para pavimentacion y techado',
            'Fabricacion de materiales para muros',
            'Fabricacion de mechas para minas',
            'Fabricacion de medallas insignias y placas',
            'Fabricacion de medias',
            'Fabricacion de mesas de billar',
            'Fabricacion de molinos para granos',
            'Fabricacion de mosaicos terrazos y granito',
            'Fabricacion de muebles de madera',
            'Fabricacion de muebles de material sintetico',
            'Fabricacion de muebles y articulos sanitarios',
            'Fabricacion de muelles y resortes para vehiculos',
            'Fabricacion de municiones para caza',
            'Fabricacion de objetos artisticos de vidrio y cristal',
            'Fabricacion de ojillos de metal',
            'Fabricacion de otras materias colorantes',
            'Fabricacion de otras prendas exteriores de vestir para caballero',
            'Fabricacion de otras prendas exteriores de vestir para niño',
            'Fabricacion de otras substancias quimicas basicas',
            'Fabricacion de otras telas mixtas de fibras blandas',
            'Fabricacion de otros aguardientes no de caña',
            'Fabricacion de otros aparatos electricos para el hogar',
            'Fabricacion de otros articulos de alambre',
            'Fabricacion de otros articulos de algodon',
            'Fabricacion de otros articulos de aluminio',
            'Fabricacion de otros articulos de carton',
            'Fabricacion de otros articulos de cera',
            'Fabricacion de otros articulos de corcho',
            'Fabricacion de otros articulos de cuero',
            'Fabricacion de otros articulos de hule',
            'Fabricacion de otros articulos de lamina',
            'Fabricacion de otros articulos de lana',
            'Fabricacion de otros articulos de laton',
            'Fabricacion de otros articulos de madera',
            'Fabricacion de otros articulos de metal no clasificados en otra parte',
            'Fabricacion de otros articulos de papel',
            'Fabricacion de otros articulos de plastico',
            'Fabricacion de otros articulos de pluma de ave',
            'Fabricacion de otros articulos para deportes',
            'Fabricacion de otros envases de vidrio',
            'Fabricacion de otros explosivos',
            'Fabricacion de otros hilados y tejidos no sinteticos',
            'Fabricacion de otros instrumentos de medicion',
            'Fabricacion de otros juguetes de plastico',
            'Fabricacion de otros materiales de plastico',
            'Fabricacion de otros muebles de metal',
            'Fabricacion de otros objetos de cristal',
            'Fabricacion de otros preparados alimenticios derivados de cereales',
            'Fabricacion de otros productos alimenticios',
            'Fabricacion de otros productos farmaceuticos y medicamentos',
            'Fabricacion de oxigeno medicinal',
            'Fabricacion de pan y pasteles',
            'Fabricacion de pañuelos pañoletas y mascadas',
            'Fabricacion de papel',
            'Fabricacion de papel para cigarros',
            'Fabricacion de partes dispositivos y accesorios para equipo y aparatos de radio television y comunicaciones',
            'Fabricacion de partes para el sistema de frenos de vehiculos automoviles',
            'Fabricacion de partes para el sistema de transmision de vehiculos automoviles',
            'Fabricacion de partes refacciones y accesorios para motocicletas bicicletas y otros vehiculos de pedal',
            'Fabricacion de pasadores y horquillas',
            'Fabricacion de pasta de celulosa',
            'Fabricacion de pasta o pulpa para papel',
            'Fabricacion de pastas alimenticias',
            'Fabricacion de pastas para guisos',
            'Fabricacion de peines peinetas y cepillos para uso personal',
            'Fabricacion de perfiles puertas y ventanas de metal',
            'Fabricacion de perfumes y cosmeticos',
            'Fabricacion de persianas de madera',
            'Fabricacion de pieles artificiales',
            'Fabricacion de piezas metalicas por fundicion y moldeo excepto para maquinaria equipo y material de transporte',
            'Fabricacion de pilas secas',
            'Fabricacion de piloncillo',
            'Fabricacion de pinturas barnices y lacas',
            'Fabricacion de pistones bielas anillos cigüeñales y monoblocks para motores',
            'Fabricacion de pizarrones',
            'Fabricacion de planchas industriales',
            'Fabricacion de polvora',
            'Fabricacion de postes y durmientes de concreto',
            'Fabricación de prendas de vestir y otros artículos confeccionados con textiles y otros materiales excepto calzado',
            'Fabricacion de productos amoniacales',
            'Fabricación de productos de hule y de plástico',
            'Fabricación de productos de minerales no metálicos; excepto del petróleo y del carbón mineral',
            'Fabricacion de productos manufacturados no clasificados en otra parte',
            'Fabricación de productos metálicos; excepto maquinaria y equipo',
            'Fabricacion de productos petroquimicos basicos',
            'Fabricacion de productos pirotecnicos',
            'Fabricacion de productos refractarios',
            'Fabricacion de puertas y ventanas de madera',
            'Fabricacion de puros',
            'Fabricacion de queso y miel de tuna',
            'Fabricacion de radios tocadiscos grabadoras y televisores',
            'Fabricacion de rebozos y cinturones tejidos de hilo',
            'Fabricacion de refacciones para aparatos electricos',
            'Fabricacion de refacciones y accesorios automotrices',
            'Fabricacion de refacciones y maquinaria industrial',
            'Fabricacion de refrescos de frutas naturales',
            'Fabricacion de refrigeradores y equipos de calefaccion domestica',
            'Fabricacion de relojes',
            'Fabricacion de remaches',
            'Fabricacion de ropa con piel',
            'Fabricacion de ropa interior para caballero',
            'Fabricacion de rotulos',
            'Fabricacion de sabanas',
            'Fabricacion de sacos y bolsas de papel para envase',
            'Fabricacion de salsas',
            'Fabricacion de sarapes y cobijas',
            'Fabricacion de sellos de goma',
            'Fabricacion de sellos para carros de ferrocarril',
            'Fabricacion de sidra champaña y otras bebidas fermentadas excepto las malteadas',
            'Fabricacion de sombreros de palma',
            'Fabricacion de sombreros excepto de palma',
            'Fabricacion de sosa',
            'Fabricacion de sotol',
            'Fabricacion de sueteres',
            'Fabricacion de talco industrial',
            'Fabricacion de tanques para envasado de gases o liquidos',
            'Fabricacion de tapetes y alfombras',
            'Fabricacion de tapices plasticos',
            'Fabricacion de tapones de metal',
            'Fabricacion de taximetros',
            'Fabricacion de teja y tubo de arcilla',
            'Fabricacion de tejidos y torcidos de ixtle',
            'Fabricacion de tejidos y torcidos de palma',
            'Fabricacion de telas elasticas',
            'Fabricacion de telas impermeables',
            'Fabricacion de telas para tapiceria',
            'Fabricacion de tequila y mezcal',
            'Fabricacion de tinacos de asbesto',
            'Fabricacion de tintas para impresion',
            'Fabricacion de tipos para imprenta',
            'Fabricacion de tirantes',
            'Fabricacion de toallas',
            'Fabricacion de toneles y barricas de madera',
            'Fabricacion de tornillos tuercas y pijas',
            'Fabricacion de tragaluces y marquesinas',
            'Fabricacion de trajes para caballero',
            'Fabricacion de triplay y otros aglomerados de madera',
            'Fabricacion de troqueles',
            'Fabricacion de tubos de cobre plomo y aluminio',
            'Fabricacion de tubos de concreto',
            'Fabricacion de tubos de estaño',
            'Fabricacion de tubos de hierro y acero',
            'Fabricacion de uniformes',
            'Fabricacion de utensilios agricolas y herramientas de mano',
            'Fabricacion de vajillas y otros productos de alfareria y ceramica para el hogar',
            'Fabricacion de valvulas de metal',
            'Fabricacion de velas veladoras y cirios',
            'Fabricacion de vestidos y otras prendas exteriores de vestir para dama',
            'Fabricacion de vidrio',
            'Fabricacion de vinagre',
            'Fabricacion de vinos y otros licores',
            'Fabricacion de yeso',
            'Fabricacion e instalacion de equipos y aparatos de aire acondicionado calefaccion y refrigeracion',
            'Fabricacion ensamble y reparacion de aeronaves',
            'Fabricacion ensamble y reparacion de carros de ferrocarril y otro equipo ferroviario',
            'Fabricacion ensamble y reparacion de gruas montacargas y otras maquinas para transportar o levantar',
            'Fabricacion ensamble y reparacion de maquinaria equipo y tractores para las industrias extractivas y de la construccion',
            'Fabricacion ensamble y reparacion de maquinaria y equipo para la industria de alimentos y bebidas',
            'Fabricacion ensamble y reparacion de motores no electricos excepto para vehiculos automoviles',
            'Fabricacion ensamble y reparacion de transformadores motores y maquinaria y equipo para generacion y utilizacion de la energia electrica',
            'Fabricacion ensamble y reparacion de vehiculos de uso agropecuario',
            'Fabricación y beneficio de productos de tabaco',
            'Fabricación y elaboración de bebidas (agua, refrescos, cerveza, vinos y licores)',
            'Fabricacion y ensamble de automoviles y camiones',
            'Fabricación y ensamble de maquinaria, equipo, aparatos, accesorios y artículos eléctricos, electrónicos y sus partes',
            'Fabricacion y ensamble de motocicletas bicicletas y otros vehiculos de pedal',
            'Fabricacion y ensamble de otros vehiculos',
            'Fabricacion y prehidratacion de leche',
            'Fabricacion y refinacion de sebo grasas y aceites animales para uso industrial',
            'Fabricacion y reparacion de aparatos ortopedicos',
            'Fabricacion y reparacion de articulos de optica',
            'Fabricacion y reparacion de basculas y balanzas',
            'Fabricacion y reparacion de buques y barcos',
            'Fabricacion y reparacion de instrumentos de cirugia',
            'Fabricacion y reparacion de instrumentos de fisica y quimica',
            'Fabricacion y reparacion de instrumentos de ingenieria',
            'Fabricacion y reparacion de instrumentos musicales',
            'Fabricación y reparación de muebles y accesorios; excepto los de metal y los de plástico moldeado',
            'Fabricacion y reparacion de otros vehiculos acuaticos',
            'Fabricación, ensamble y reparación de maquinaria, equipo y sus partes; excepto los eléctricos',
            'Factoring',
            'Federaciones y asociaciones deportivas y otras con fines recreativos',
            'Ferrocarriles',
            'Fobaproa-ipab',
            'Formacion de praderas y potreros artificiales',
            'Forrado de botones y hebillas',
            'Fotocopiado',
            'Fundicion de fierro y acero',
            'Fundicion de metales no ferruginosos',
            'Fundicion de sebo',
            'Fundicion laminacion extrusion y estiraje de aluminio y fabricacion de soldaduras aluminotermicas',
            'Fundicion refinacion laminacion extrusion y estiraje de cobre y sus aleaciones',
            'Galerias de artes graficas y museos',
            'Galvanizacion de lamina',
            'Galvanizacion de tuberia',
            'Ganadero',
            'Generacion y suministro de energia electrica',
            'Generación, transmisión y distribución de energía eléctrica',
            'Gobierno estatal',
            'Gobierno extranjero',
            'Gobierno federal',
            'Gobierno municipal',
            'Grabacion de discos y cintas',
            'Grabacion de sonido en peliculas',
            'Grabado e impresion en piedra vidrio y otros materiales litografia y fotolitografia',
            'Grabado e impresion fotomecanica mediante agua fuerte(heliograbado)',
            'Grabado en metal (fabricacion de cliches y fotograbado)',
            'Hidrogenadora de productos diversos',
            'Hipodromo',
            'Horno de cal',
            'Hospitales sanatorios clinicas y maternidades',
            'Hotel',
            'Impermeabilizacion de inmuebles',
            'Imprenta ( tipografia)',
            'Impresion mediante cilindros (rotograbado)',
            'Impresion mediante cilindros de caucho',
            'Industria del papel',
            'Industria química',
            'Industria textil (fabricación de: hilados y tejidos)',
            'Industria y productos de madera y corcho; excepto muebles',
            'Industrializacion de basura',
            'Industrias editorial, de impresión y conexas',
            'Industrias metálicas básicas',
            'Ingenio azucarero',
            'Inseminacion artificial y otros servicios de ganaderia',
            'Instalaciones de sistemas de aire acondicionado y calefaccion y otras instalaciones analogas',
            'Instalaciones del sistema electrico incluye sistemas de intercomunicacion',
            'Instituciones financieras del extranjero',
            'Irrigacion de tierras',
            'Juegos de feria',
            'Laboratorios cinematograficos',
            'Laboratorios de analisis clinicos',
            'Labrado y colocacion de piedra',
            'Lavanderia',
            'Menores banca desarrollo',
            'Menores comunicaciones',
            'Menores construccion de vivienda residencial',
            'Molino de arroz',
            'Molino de avena',
            'Molino de cebada',
            'Molino de maiz',
            'Molino de nixtamal',
            'Molino de otros cereales',
            'Molino de trigo',
            'Molino para otros granos excepto cereales',
            'Molino y tostador de cafe',
            'Montepio',
            'Negocios relacionados con internet (u.i.f)',
            'Neveria y refresqueria',
            'No clasificada (uso exclusivo cnbv)',
            'Operaciones de arrendamiento capitalizable',
            'Orfebreria',
            'Organizaciones civicas',
            'Organizaciones de abogados medicos ingenieros y otras asociaciones de profesionales',
            'Organizaciones laborales y sindicales',
            'Organizaciones politicas',
            'Organizaciones religiosas',
            'Otras industrias manufactureras (joyeria, articulos de escritorio, fotograficos, para dentista, para optica, deportivos)',
            'Otros créditos al consumo',
            'Otros cultivos permanentes',
            'Otros servicios de acabado prestados por subcontratistas',
            'Otros servicios de telecomunicaciones (excepto radiodifusion y television)',
            'Panteon',
            'Pasteurizacion homogeneizacion y envasado de leche',
            'Pavimentacion',
            'Perforacion de norias y pozos para agua',
            'Perforacion de pozos petroleros y de gas',
            'Pesca',
            'Picado de tabaco',
            'Pidiregas energia electrica',
            'Pidiregas petroleo',
            'Planta metalurgica',
            'Plantacion y reforestacion',
            'Plaza de toros',
            'Premezclado y colado de concreto',
            'Preparacion de tierras de cultivo y otros servicios agricolas',
            'Preparacion de visceras para industrias no alimenticias',
            'Preparación y servicio de alimentos y bebidas',
            'Prestacion de otros servicios tecnicos',
            'Prestacion de servicios publicos y sociales',
            'Prestamista',
            'Prestamos al personal de la institucion',
            'Prestamos para la Adquisición de vivienda para acreditados de ingresos minimos',
            'Prestamos para la Adquisición de vivienda tanto de interes social como provenientes de la reserva para pensiones del personal',
            'Prestamos para la construccion de vivienda para acreditados de ingresos minimos',
            'Prestamos para la construccion de vivienda tanto de interes social como provenientes de la reserva para pensiones del personal',
            'Produccion de peliculas',
            'Promocion de espectaculos deportivos',
            'Promocion de espectaculos taurinos',
            'Purificacion de agua excepto captacion tratamiento conduccion y distribucion de agua potable',
            'Quehaceres del hogar',
            'Radiodifusora',
            'Rastro',
            'Recoleccion de algas y otras plantas acuaticas',
            'Recoleccion de conchas huevos corales esponjas y perlas',
            'Refinación de petróleo y derivados del carbón mineral',
            'Refinacion de sal',
            'Refrigeracion de carnes',
            'Regeneracion de hule',
            'Renta de vehiculos aereos',
            'Representacion de artistas',
            'Representante casas extranjeras',
            'Representante casas nacionales',
            'Restaurante',
            'Sala de cine',
            'Salchichoneria',
            'Salon de belleza',
            'Salon de billar',
            'Salon de boliche',
            'Salon de fiestas',
            'Servicio de corredores de bienes raices',
            'Servicio de investigacion de mercado solvencia financiera, de patentes y marcas industriales y otros similares',
            'Servicio de reparacion de vehiculos de traccion animal y propulsion a mano',
            'Servicios administrativos de tramite y cobranza; incluso escritorios publicos',
            'Servicios colaterales a instituciones financieras y de seguros',
            'Servicios conexos al transporte',
            'Servicios de administración pública, defensa y seguridad social',
            'Servicios de agencias de colocacion y seleccion de personal',
            'Servicios de alimentos en lencerias taquerias y torterias',
            'Servicios de almacenamiento y refrigeracion',
            'Servicios de alojamiento en moteles',
            'Servicios de alojamiento temporal',
            'Servicios de alquiler a empresas',
            'Servicios de analisis de sistemas y procesamiento electrónico de datos',
            'Servicios de asesoria y estudios tecnicos de arquitectura e ingenieria (incluso diseño industrial)',
            'Servicios de bascula y de grua para vehiculos',
            'Servicios de bibliotecas museos jardines botanicos y otros servicios de difusion cultural',
            'Servicios de bolerias masajistas sanitarios publicos y otros servicios de aseo y limpieza',
            'Servicios de bufetes juridicos',
            'Servicios de capacitacion tecnica de oficios y artesanias',
            'Servicios de consultorios y clinicas dentales',
            'Servicios de contaduria y auditoria; incluso teneduria de libros',
            'Servicios de copias fotostaticas xerografitas y similares',
            'Servicios de cortado estimacion del volumen de madera proteccion de bosques y otros servicios relativos a la explotacion forestal',
            'Servicios de enseñanza comercial y de idioma',
            'Servicios de enseñanza de musica danza y otras artes cultura fisica manejo de vehiculos y otros especializados',
            'Servicios de enseñanza prerrimaria y primaria',
            'Servicios de enseñanza secundaria',
            'Servicios de enseñanza, investigación científica y difusión cultural',
            'Servicios de fisioterapia bancos de sangre y otros servicios medicos',
            'Servicios de fondos y fideicomisos de fomento economico',
            'Servicios de fumigacion desinfeccion y control de plagas',
            'Servicios de instalacion y mantenimiento de maquinaria y equipo por empresas especializadas',
            'Servicios de instituciones de crédito, organizaciones auxiliares e instituciones de seguros y fianzas',
            'Servicios de investigacion cientifica',
            'Servicios de la banca nacional',
            'Servicios de la banca nacional por operaciones de call money',
            'Servicios de la banca privada y mixta multiple',
            'Servicios de la banca privada y mixta multiple por operaciones de call money',
            'Servicios de laboratorios de radiologia y radioscopia',
            'Servicios de lavado y lubricacion de automoviles',
            'Servicios de notarias publicas',
            'Servicios de oficinas y representaciones de otros paises que gozan de extraterritorialidad',
            'Servicios de organizaciones internacionales y otros organismos extraterritoriales (u.i.f)',
            'Servicios de pesquerias maritimas y de agua dulce por contrato',
            'Servicios de pintado y tapizado de inmuebles',
            'Servicios de reparacion de carrocerias pintura tapiceria hojalateria y cristales de automoviles',
            'Servicios de reparacion de motocicletas y bicicletas',
            'Servicios de reparacion de relojes y joyas',
            'Servicios de reparacion especializado en partes de automoviles excepto reconstruccion de motores y carrocerias',
            'Servicios en balnearios y albercas',
            'Servicios en merenderos cenadurias y preparacion de antojitos y platillos regionales',
            'Servicios en ostionerias y preparacion de otros mariscos y pescados',
            'Servicios en pulquerias',
            'Servicios especiales prestados por subcontratistas (demoliciones, carpinteria, impermiabilización, inst eslectricas, pintura, plomeria)',
            'Servicios medico general y especializado en consultorios',
            'Servicios médicos, de asistencia social y veterinarios',
            'Servicios personales, para el hogar y diversos',
            'Servicios postales',
            'Servicios profesionales y técnicos',
            'Servicios recreativos y de esparcimiento',
            'Servicios relacionados con el transporte en aeronaves con matricula extranjera',
            'Servicios relacionados con el transporte en general',
            'Servicios relacionados con inmuebles',
            'Servicios veterinarios en clinicas y consultorios incluso zootecnistas pensiones de animales y otros servicios auxiliares',
            'Servicios y explotacion de playas y parques de descanso clubes de excursionismo de caza y pesca incluso alquiler de lanchas, caballos, calesas y otros con fines recreativos y deportivos',
            'Silvicultura',
            'Sociedades cooperativas',
            'Sociedades de ahorro y crédito popular',
            'Sociedades de ahorro y prestamo',
            'Sociedades de inversion',
            'Sociedades financieras de objeto limitado',
            'Sociedades financieras de objeto multiple no reguladas',
            'Sociedades financieras de objeto multiple reguladas',
            'Talabarteria',
            'Tallado de piedras preciosas',
            'Taller de cobrizado',
            'Taller de confeccion de vestidos',
            'Taller de cromado y niquelado',
            'Taller de esmaltado',
            'Taller de herreria',
            'Taller de hojalateria',
            'Taller de marmoleria',
            'Taller de plomeria',
            'Taller de reparacion de aparatos electricos y electrónicos industriales y comerciales',
            'Taller de reparacion de articulos electricos y electrónicos para el hogar',
            'Taller de reparacion de calzado',
            'Taller de reparacion de paraguas y sombrillas',
            'Taller de reparacion de ropa y medias',
            'Taller de reparacion de sombreros',
            'Taller de reparacion general de automoviles y camiones',
            'Taller de sastreria',
            'Taller de tapiceria',
            'Taller mecanico de fabricacion y reparacion de partes industriales',
            'Tarjeta de crédito',
            'Taxidermista',
            'Teatro',
            'Teledifusora',
            'Tienda de abarrotes y miscelanea',
            'Tienda de autoservicio',
            'Tiendas de departamentos especializados excepto de comestibles',
            'Tintoreria y planchaduria',
            'Tortilleria',
            'Transmisores de dinero o dispersores/cambistas o centros cambiarios/casas de empeño (u.i.f)',
            'Transportacion aerea de pasajeros',
            'Transporte aéreo',
            'Transporte de carga foranea',
            'Transporte en autobus foraneo de pasajeros',
            'Transporte en autobus urbano y suburbano de pasajeros',
            'Transporte en automovil de ruleteo',
            'Transporte en automovil de ruta fija',
            'Transporte en automoviles de sitio y turismo',
            'Transporte en ferrocarril urbano (metro)',
            'Transporte fluvial y lacustre',
            'Transporte por agua',
            'Transporte por ductos',
            'Transporte terrestre',
            'Transportes marítimos de cabotaje',
            'Tranvias y trolebuses',
            'Tratamiento y envase de miel de abeja',
            'Uniones de crédito nacionales',
            'Uniones de crédito privadas',
            'Urbanizacion',
            'Usuarios menores Adquisición de vivienda residencial',
            'Usuarios menores Adquisición de vivienda tipo medio',
            'Usuarios menores agricultura',
            'Usuarios menores banca comercial',
            'Usuarios menores cinematografia y esparcimiento',
            'Usuarios menores comercio',
            'Usuarios menores construccion de vivienda tipo medio',
            'Usuarios menores construccion diferente a vivienda',
            'Usuarios menores de industria siderurgica y productos metalicos',
            'Usuarios menores de servicios',
            'Usuarios menores energia electrica',
            'Usuarios menores fabricacion maquinaria y articulos electricos',
            'Usuarios menores ganaderia',
            'Usuarios menores gobierno estatal y municipal',
            'Usuarios menores gobierno federal',
            'Usuarios menores industria manufacturera',
            'Usuarios menores industria productos de minerales no metalicos',
            'Usuarios menores mineria',
            'Usuarios menores otras actividades',
            'Usuarios menores otros intermediarios financieros privados',
            'Usuarios menores otros intermediarios financieros publicos',
            'Usuarios menores petroleo',
            'Usuarios menores por operaciones de reporto',
            'Usuarios menores servicios medicos',
            'Usuarios menores servicios profesionales y tecnicos',
            'Usuarios menores silvicultura, pesca y preservacion de animales salvajes',
            'Usuarios menores transportes',
            'Usuarios menores turismo',
            'Venta de tarjetas telefonicas prepagadas (u.i.f)',
            'Venta y distribucion de despensas familiares',
            'Vulcanización de llantas y cámaras',
        ];

        $data = [];
        foreach ($ocupaciones as $index => $ocupacion) {
            $data[] = [
                'IDOcupacionGiro' => $index + 1,
                'OcupacionGiro' => $ocupacion,
            ];
        }

        foreach (array_chunk($data, 100) as $chunk) {
            DB::table('catocupacionesgiros')->insert($chunk);
        }
    }
}