<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Lista abreviada de nacionalidades según ISO 3166-1 alpha-2.
        // Puedes expandir según necesidades del proyecto.
        $nacionalidades = [
            ['IDNacionalidad' => 'AF', 'Nacionalidad' => 'Afgana'],
            ['IDNacionalidad' => 'AX', 'Nacionalidad' => 'Ålandesa'],
            ['IDNacionalidad' => 'AL', 'Nacionalidad' => 'Albanesa'],
            ['IDNacionalidad' => 'DZ', 'Nacionalidad' => 'Argelina'],
            ['IDNacionalidad' => 'AS', 'Nacionalidad' => 'Samoana americana'],
            ['IDNacionalidad' => 'AD', 'Nacionalidad' => 'Andorrana'],
            ['IDNacionalidad' => 'AO', 'Nacionalidad' => 'Angoleña'],
            ['IDNacionalidad' => 'AI', 'Nacionalidad' => 'Anguilense'],
            ['IDNacionalidad' => 'AQ', 'Nacionalidad' => 'Antártica'],
            ['IDNacionalidad' => 'AG', 'Nacionalidad' => 'Antiguana'],
            ['IDNacionalidad' => 'AR', 'Nacionalidad' => 'Argentina'],
            ['IDNacionalidad' => 'AM', 'Nacionalidad' => 'Armenia'],
            ['IDNacionalidad' => 'AW', 'Nacionalidad' => 'Arubeña'],
            ['IDNacionalidad' => 'AU', 'Nacionalidad' => 'Australiana'],
            ['IDNacionalidad' => 'AT', 'Nacionalidad' => 'Austriaca'],
            ['IDNacionalidad' => 'AZ', 'Nacionalidad' => 'Azerbaiyana'],

            ['IDNacionalidad' => 'BS', 'Nacionalidad' => 'Bahameña'],
            ['IDNacionalidad' => 'BH', 'Nacionalidad' => 'Bareiní'],
            ['IDNacionalidad' => 'BD', 'Nacionalidad' => 'Bangladesí'],
            ['IDNacionalidad' => 'BB', 'Nacionalidad' => 'Barbadense'],
            ['IDNacionalidad' => 'BY', 'Nacionalidad' => 'Bielorrusa'],
            ['IDNacionalidad' => 'BE', 'Nacionalidad' => 'Belga'],
            ['IDNacionalidad' => 'BZ', 'Nacionalidad' => 'Beliceña'],
            ['IDNacionalidad' => 'BJ', 'Nacionalidad' => 'Beninesa'],
            ['IDNacionalidad' => 'BM', 'Nacionalidad' => 'Bermudeña'],
            ['IDNacionalidad' => 'BT', 'Nacionalidad' => 'Butanesa'],
            ['IDNacionalidad' => 'BO', 'Nacionalidad' => 'Boliviana'],
            ['IDNacionalidad' => 'BQ', 'Nacionalidad' => 'Caribe neerlandés'],
            ['IDNacionalidad' => 'BA', 'Nacionalidad' => 'Bosnia'],
            ['IDNacionalidad' => 'BW', 'Nacionalidad' => 'Botsuana'],
            ['IDNacionalidad' => 'BV', 'Nacionalidad' => 'Isla Bouvet'],
            ['IDNacionalidad' => 'BR', 'Nacionalidad' => 'Brasileña'],
            ['IDNacionalidad' => 'IO', 'Nacionalidad' => 'Territorio británico del Índico'],
            ['IDNacionalidad' => 'BN', 'Nacionalidad' => 'Bruneana'],
            ['IDNacionalidad' => 'BG', 'Nacionalidad' => 'Búlgara'],
            ['IDNacionalidad' => 'BF', 'Nacionalidad' => 'Burkinesa'],
            ['IDNacionalidad' => 'BI', 'Nacionalidad' => 'Burundesa'],

            ['IDNacionalidad' => 'KH', 'Nacionalidad' => 'Camboyana'],
            ['IDNacionalidad' => 'CM', 'Nacionalidad' => 'Camerunesa'],
            ['IDNacionalidad' => 'CA', 'Nacionalidad' => 'Canadiense'],
            ['IDNacionalidad' => 'CV', 'Nacionalidad' => 'Caboverdiana'],
            ['IDNacionalidad' => 'KY', 'Nacionalidad' => 'Caimense'],
            ['IDNacionalidad' => 'CF', 'Nacionalidad' => 'Centroafricana'],
            ['IDNacionalidad' => 'TD', 'Nacionalidad' => 'Chadiana'],
            ['IDNacionalidad' => 'CL', 'Nacionalidad' => 'Chilena'],
            ['IDNacionalidad' => 'CN', 'Nacionalidad' => 'China'],
            ['IDNacionalidad' => 'CX', 'Nacionalidad' => 'Isla de Navidad'],
            ['IDNacionalidad' => 'CC', 'Nacionalidad' => 'Islas Cocos'],
            ['IDNacionalidad' => 'CO', 'Nacionalidad' => 'Colombiana'],
            ['IDNacionalidad' => 'KM', 'Nacionalidad' => 'Comorense'],
            ['IDNacionalidad' => 'CG', 'Nacionalidad' => 'Congoleña'],
            ['IDNacionalidad' => 'CD', 'Nacionalidad' => 'Congoleña (RDC)'],
            ['IDNacionalidad' => 'CK', 'Nacionalidad' => 'Islas Cook'],
            ['IDNacionalidad' => 'CR', 'Nacionalidad' => 'Costarricense'],
            ['IDNacionalidad' => 'CI', 'Nacionalidad' => 'Marfileña'],
            ['IDNacionalidad' => 'HR', 'Nacionalidad' => 'Croata'],
            ['IDNacionalidad' => 'CU', 'Nacionalidad' => 'Cubana'],
            ['IDNacionalidad' => 'CW', 'Nacionalidad' => 'Curazoleña'],
            ['IDNacionalidad' => 'CY', 'Nacionalidad' => 'Chipriota'],
            ['IDNacionalidad' => 'CZ', 'Nacionalidad' => 'Checa'],

            ['IDNacionalidad' => 'DK', 'Nacionalidad' => 'Danesa'],
            ['IDNacionalidad' => 'DJ', 'Nacionalidad' => 'Yibutiana'],
            ['IDNacionalidad' => 'DM', 'Nacionalidad' => 'Dominicense'],
            ['IDNacionalidad' => 'DO', 'Nacionalidad' => 'Dominicana'],

            ['IDNacionalidad' => 'EC', 'Nacionalidad' => 'Ecuatoriana'],
            ['IDNacionalidad' => 'EG', 'Nacionalidad' => 'Egipcia'],
            ['IDNacionalidad' => 'SV', 'Nacionalidad' => 'Salvadoreña'],
            ['IDNacionalidad' => 'GQ', 'Nacionalidad' => 'Ecuatoguineana'],
            ['IDNacionalidad' => 'ER', 'Nacionalidad' => 'Eritrea'],
            ['IDNacionalidad' => 'EE', 'Nacionalidad' => 'Estonia'],
            ['IDNacionalidad' => 'SZ', 'Nacionalidad' => 'Suazi'],
            ['IDNacionalidad' => 'ET', 'Nacionalidad' => 'Etíope'],

            ['IDNacionalidad' => 'FK', 'Nacionalidad' => 'Malvinense'],
            ['IDNacionalidad' => 'FO', 'Nacionalidad' => 'Feroesa'],
            ['IDNacionalidad' => 'FJ', 'Nacionalidad' => 'Fiyiana'],
            ['IDNacionalidad' => 'FI', 'Nacionalidad' => 'Finlandesa'],
            ['IDNacionalidad' => 'FR', 'Nacionalidad' => 'Francesa'],

            ['IDNacionalidad' => 'GF', 'Nacionalidad' => 'Guayanesa francesa'],
            ['IDNacionalidad' => 'PF', 'Nacionalidad' => 'Polinesia francesa'],
            ['IDNacionalidad' => 'TF', 'Nacionalidad' => 'Tierras australes francesas'],
            ['IDNacionalidad' => 'GA', 'Nacionalidad' => 'Gabonesa'],
            ['IDNacionalidad' => 'GM', 'Nacionalidad' => 'Gambiana'],
            ['IDNacionalidad' => 'GE', 'Nacionalidad' => 'Georgiana'],
            ['IDNacionalidad' => 'DE', 'Nacionalidad' => 'Alemana'],
            ['IDNacionalidad' => 'GH', 'Nacionalidad' => 'Ghanesa'],
            ['IDNacionalidad' => 'GI', 'Nacionalidad' => 'Gibraltareña'],
            ['IDNacionalidad' => 'GR', 'Nacionalidad' => 'Griega'],
            ['IDNacionalidad' => 'GL', 'Nacionalidad' => 'Groenlandesa'],
            ['IDNacionalidad' => 'GD', 'Nacionalidad' => 'Granadina'],
            ['IDNacionalidad' => 'GP', 'Nacionalidad' => 'Guadalupeña'],
            ['IDNacionalidad' => 'GU', 'Nacionalidad' => 'Guameña'],
            ['IDNacionalidad' => 'GT', 'Nacionalidad' => 'Guatemalteca'],
            ['IDNacionalidad' => 'GG', 'Nacionalidad' => 'Guernesey'],
            ['IDNacionalidad' => 'GN', 'Nacionalidad' => 'Guineana'],
            ['IDNacionalidad' => 'GW', 'Nacionalidad' => 'Guineana-bisauense'],
            ['IDNacionalidad' => 'GY', 'Nacionalidad' => 'Guyanesa'],

            ['IDNacionalidad' => 'HT', 'Nacionalidad' => 'Haitiana'],
            ['IDNacionalidad' => 'HM', 'Nacionalidad' => 'Islas Heard y McDonald'],
            ['IDNacionalidad' => 'VA', 'Nacionalidad' => 'Vaticana'],
            ['IDNacionalidad' => 'HN', 'Nacionalidad' => 'Hondureña'],
            ['IDNacionalidad' => 'HK', 'Nacionalidad' => 'Hongkonesa'],
            ['IDNacionalidad' => 'HU', 'Nacionalidad' => 'Húngara'],

            ['IDNacionalidad' => 'IS', 'Nacionalidad' => 'Islandesa'],
            ['IDNacionalidad' => 'IN', 'Nacionalidad' => 'India'],
            ['IDNacionalidad' => 'ID', 'Nacionalidad' => 'Indonesia'],
            ['IDNacionalidad' => 'IR', 'Nacionalidad' => 'Iraní'],
            ['IDNacionalidad' => 'IQ', 'Nacionalidad' => 'Iraquí'],
            ['IDNacionalidad' => 'IE', 'Nacionalidad' => 'Irlandesa'],
            ['IDNacionalidad' => 'IM', 'Nacionalidad' => 'Manesa'],
            ['IDNacionalidad' => 'IL', 'Nacionalidad' => 'Israelí'],
            ['IDNacionalidad' => 'IT', 'Nacionalidad' => 'Italiana'],

            ['IDNacionalidad' => 'JM', 'Nacionalidad' => 'Jamaiquina'],
            ['IDNacionalidad' => 'JP', 'Nacionalidad' => 'Japonesa'],
            ['IDNacionalidad' => 'JE', 'Nacionalidad' => 'Jerseya'],
            ['IDNacionalidad' => 'JO', 'Nacionalidad' => 'Jordana'],
            ['IDNacionalidad' => 'KZ', 'Nacionalidad' => 'Kazaja'],
            ['IDNacionalidad' => 'KE', 'Nacionalidad' => 'Keniana'],
            ['IDNacionalidad' => 'KI', 'Nacionalidad' => 'Kiribatiana'],
            ['IDNacionalidad' => 'KP', 'Nacionalidad' => 'Norcoreana'],
            ['IDNacionalidad' => 'KR', 'Nacionalidad' => 'Surcoreana'],
            ['IDNacionalidad' => 'KW', 'Nacionalidad' => 'Kuwaití'],
            ['IDNacionalidad' => 'KG', 'Nacionalidad' => 'Kirguisa'],

            ['IDNacionalidad' => 'LA', 'Nacionalidad' => 'Laosiana'],
            ['IDNacionalidad' => 'LV', 'Nacionalidad' => 'Letona'],
            ['IDNacionalidad' => 'LB', 'Nacionalidad' => 'Libanesa'],
            ['IDNacionalidad' => 'LS', 'Nacionalidad' => 'Lesotense'],
            ['IDNacionalidad' => 'LR', 'Nacionalidad' => 'Liberiana'],
            ['IDNacionalidad' => 'LY', 'Nacionalidad' => 'Libia'],
            ['IDNacionalidad' => 'LI', 'Nacionalidad' => 'Liechtensteiniana'],
            ['IDNacionalidad' => 'LT', 'Nacionalidad' => 'Lituana'],
            ['IDNacionalidad' => 'LU', 'Nacionalidad' => 'Luxemburguesa'],

            ['IDNacionalidad' => 'MO', 'Nacionalidad' => 'Macaense'],
            ['IDNacionalidad' => 'MG', 'Nacionalidad' => 'Malgache'],
            ['IDNacionalidad' => 'MW', 'Nacionalidad' => 'Malauí'],
            ['IDNacionalidad' => 'MY', 'Nacionalidad' => 'Malasia'],
            ['IDNacionalidad' => 'MV', 'Nacionalidad' => 'Maldiva'],
            ['IDNacionalidad' => 'ML', 'Nacionalidad' => 'Maliense'],
            ['IDNacionalidad' => 'MT', 'Nacionalidad' => 'Maltesa'],
            ['IDNacionalidad' => 'MH', 'Nacionalidad' => 'Marshalense'],
            ['IDNacionalidad' => 'MQ', 'Nacionalidad' => 'Martiniqueña'],
            ['IDNacionalidad' => 'MR', 'Nacionalidad' => 'Mauritana'],
            ['IDNacionalidad' => 'MU', 'Nacionalidad' => 'Mauriciana'],
            ['IDNacionalidad' => 'YT', 'Nacionalidad' => 'Mayotense'],
            ['IDNacionalidad' => 'MX', 'Nacionalidad' => 'Mexicana'],
            ['IDNacionalidad' => 'FM', 'Nacionalidad' => 'Micronesia'],
            ['IDNacionalidad' => 'MD', 'Nacionalidad' => 'Moldava'],
            ['IDNacionalidad' => 'MC', 'Nacionalidad' => 'Monegasca'],
            ['IDNacionalidad' => 'MN', 'Nacionalidad' => 'Mongola'],
            ['IDNacionalidad' => 'ME', 'Nacionalidad' => 'Montenegrina'],
            ['IDNacionalidad' => 'MS', 'Nacionalidad' => 'Montserratense'],
            ['IDNacionalidad' => 'MA', 'Nacionalidad' => 'Marroquí'],
            ['IDNacionalidad' => 'MZ', 'Nacionalidad' => 'Mozambiqueña'],
            ['IDNacionalidad' => 'MM', 'Nacionalidad' => 'Birmana'],

            ['IDNacionalidad' => 'NA', 'Nacionalidad' => 'Namibia'],
            ['IDNacionalidad' => 'NR', 'Nacionalidad' => 'Nauruana'],
            ['IDNacionalidad' => 'NP', 'Nacionalidad' => 'Nepalesa'],
            ['IDNacionalidad' => 'NL', 'Nacionalidad' => 'Neerlandesa'],
            ['IDNacionalidad' => 'NC', 'Nacionalidad' => 'Neocaledonia'],
            ['IDNacionalidad' => 'NZ', 'Nacionalidad' => 'Neozelandesa'],
            ['IDNacionalidad' => 'NI', 'Nacionalidad' => 'Nicaragüense'],
            ['IDNacionalidad' => 'NE', 'Nacionalidad' => 'Nigerina'],
            ['IDNacionalidad' => 'NG', 'Nacionalidad' => 'Nigeriana'],
            ['IDNacionalidad' => 'NU', 'Nacionalidad' => 'Niue'],
            ['IDNacionalidad' => 'NF', 'Nacionalidad' => 'Norfolk'],
            ['IDNacionalidad' => 'MP', 'Nacionalidad' => 'Mariana del norte'],
            ['IDNacionalidad' => 'NO', 'Nacionalidad' => 'Noruega'],
            ['IDNacionalidad' => 'OM', 'Nacionalidad' => 'Omaní'],

            ['IDNacionalidad' => 'PK', 'Nacionalidad' => 'Pakistaní'],
            ['IDNacionalidad' => 'PW', 'Nacionalidad' => 'Palaosiana'],
            ['IDNacionalidad' => 'PS', 'Nacionalidad' => 'Palestina'],
            ['IDNacionalidad' => 'PA', 'Nacionalidad' => 'Panameña'],
            ['IDNacionalidad' => 'PG', 'Nacionalidad' => 'Papú'],
            ['IDNacionalidad' => 'PY', 'Nacionalidad' => 'Paraguaya'],
            ['IDNacionalidad' => 'PE', 'Nacionalidad' => 'Peruana'],
            ['IDNacionalidad' => 'PH', 'Nacionalidad' => 'Filipina'],
            ['IDNacionalidad' => 'PN', 'Nacionalidad' => 'Pitcairn'],
            ['IDNacionalidad' => 'PL', 'Nacionalidad' => 'Polaca'],
            ['IDNacionalidad' => 'PT', 'Nacionalidad' => 'Portuguesa'],
            ['IDNacionalidad' => 'PR', 'Nacionalidad' => 'Puertorriqueña'],

            ['IDNacionalidad' => 'QA', 'Nacionalidad' => 'Catarí'],
            ['IDNacionalidad' => 'RE', 'Nacionalidad' => 'Reunionense'],
            ['IDNacionalidad' => 'RO', 'Nacionalidad' => 'Rumana'],
            ['IDNacionalidad' => 'RU', 'Nacionalidad' => 'Rusa'],
            ['IDNacionalidad' => 'RW', 'Nacionalidad' => 'Ruandesa'],

            ['IDNacionalidad' => 'WS', 'Nacionalidad' => 'Samoana'],
            ['IDNacionalidad' => 'SM', 'Nacionalidad' => 'Sanmarinense'],
            ['IDNacionalidad' => 'ST', 'Nacionalidad' => 'Santomense'],
            ['IDNacionalidad' => 'SA', 'Nacionalidad' => 'Saudí'],
            ['IDNacionalidad' => 'SN', 'Nacionalidad' => 'Senegalesa'],
            ['IDNacionalidad' => 'RS', 'Nacionalidad' => 'Serbia'],
            ['IDNacionalidad' => 'SC', 'Nacionalidad' => 'Seychellense'],
            ['IDNacionalidad' => 'SL', 'Nacionalidad' => 'Sierraleonesa'],
            ['IDNacionalidad' => 'SG', 'Nacionalidad' => 'Singapurense'],
            ['IDNacionalidad' => 'SX', 'Nacionalidad' => 'Sanmartinense'],
            ['IDNacionalidad' => 'SK', 'Nacionalidad' => 'Eslovaca'],
            ['IDNacionalidad' => 'SI', 'Nacionalidad' => 'Eslovena'],
            ['IDNacionalidad' => 'SB', 'Nacionalidad' => 'Salomonense'],
            ['IDNacionalidad' => 'SO', 'Nacionalidad' => 'Somalí'],
            ['IDNacionalidad' => 'ZA', 'Nacionalidad' => 'Sudafricana'],
            ['IDNacionalidad' => 'GS', 'Nacionalidad' => 'Georgia del Sur'],
            ['IDNacionalidad' => 'SS', 'Nacionalidad' => 'Sursudanesa'],
            ['IDNacionalidad' => 'ES', 'Nacionalidad' => 'Española'],
            ['IDNacionalidad' => 'LK', 'Nacionalidad' => 'Ceilanesa'],
            ['IDNacionalidad' => 'SD', 'Nacionalidad' => 'Sudanesa'],
            ['IDNacionalidad' => 'SR', 'Nacionalidad' => 'Surinamesa'],
            ['IDNacionalidad' => 'SJ', 'Nacionalidad' => 'Svalbard'],
            ['IDNacionalidad' => 'SE', 'Nacionalidad' => 'Sueca'],
            ['IDNacionalidad' => 'CH', 'Nacionalidad' => 'Suiza'],
            ['IDNacionalidad' => 'SY', 'Nacionalidad' => 'Siria'],

            ['IDNacionalidad' => 'TW', 'Nacionalidad' => 'Taiwanesa'],
            ['IDNacionalidad' => 'TJ', 'Nacionalidad' => 'Tayika'],
            ['IDNacionalidad' => 'TZ', 'Nacionalidad' => 'Tanzana'],
            ['IDNacionalidad' => 'TH', 'Nacionalidad' => 'Tailandesa'],
            ['IDNacionalidad' => 'TL', 'Nacionalidad' => 'Timorense'],
            ['IDNacionalidad' => 'TG', 'Nacionalidad' => 'Togolesa'],
            ['IDNacionalidad' => 'TK', 'Nacionalidad' => 'Tokelau'],
            ['IDNacionalidad' => 'TO', 'Nacionalidad' => 'Tongana'],
            ['IDNacionalidad' => 'TT', 'Nacionalidad' => 'Trinitense'],
            ['IDNacionalidad' => 'TN', 'Nacionalidad' => 'Tunecina'],
            ['IDNacionalidad' => 'TR', 'Nacionalidad' => 'Turca'],
            ['IDNacionalidad' => 'TM', 'Nacionalidad' => 'Turcomana'],
            ['IDNacionalidad' => 'TC', 'Nacionalidad' => 'Turca y Caicos'],
            ['IDNacionalidad' => 'TV', 'Nacionalidad' => 'Tuvaluana'],

            ['IDNacionalidad' => 'UG', 'Nacionalidad' => 'Ugandesa'],
            ['IDNacionalidad' => 'UA', 'Nacionalidad' => 'Ucraniana'],
            ['IDNacionalidad' => 'AE', 'Nacionalidad' => 'Emiratí'],
            ['IDNacionalidad' => 'GB', 'Nacionalidad' => 'Británica'],
            ['IDNacionalidad' => 'US', 'Nacionalidad' => 'Estadounidense'],
            ['IDNacionalidad' => 'UM', 'Nacionalidad' => 'Islas menores de EE.UU.'],
            ['IDNacionalidad' => 'UY', 'Nacionalidad' => 'Uruguaya'],
            ['IDNacionalidad' => 'UZ', 'Nacionalidad' => 'Uzbeca'],

            ['IDNacionalidad' => 'VU', 'Nacionalidad' => 'Vanuatuense'],
            ['IDNacionalidad' => 'VE', 'Nacionalidad' => 'Venezolana'],
            ['IDNacionalidad' => 'VN', 'Nacionalidad' => 'Vietnamita'],
            ['IDNacionalidad' => 'VG', 'Nacionalidad' => 'Islas Vírgenes británicas'],
            ['IDNacionalidad' => 'VI', 'Nacionalidad' => 'Islas Vírgenes estadounidenses'],

            ['IDNacionalidad' => 'WF', 'Nacionalidad' => 'Wallisiana'],
            ['IDNacionalidad' => 'EH', 'Nacionalidad' => 'Saharaui'],
            ['IDNacionalidad' => 'YE', 'Nacionalidad' => 'Yemení'],
            ['IDNacionalidad' => 'ZM', 'Nacionalidad' => 'Zambiana'],
            ['IDNacionalidad' => 'ZW', 'Nacionalidad' => 'Zimbabuense'],
        ];

        DB::table('catNacionalidad')->insert($nacionalidades);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Elimina las nacionalidades insertadas por sus IDs.
        $ids = [
            'MX',
            'US',
            'CA',
            'AR',
            'BR',
            'CL',
            'CO',
            'ES',
            'FR',
            'DE',
            'IT',
            'GB',
            'JP',
            'CN',
            'IN',
        ];
        DB::table('catNacionalidad')->whereIn('IDNacionalidad', $ids)->delete();
    }
};
