<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Facades\Schema;


return new class extends Migration
{
    public function up(): void
    {
        $now = Carbon::now();

        DB::table('tbClientes')->insert([
            [
                'IDCliente' => 14,
                'ckAgente' => 1,
                'RFC' => 'GAGL620810S43',
                'Nombre' => 'Lorenzo',
                'ApellidoPaterno' => 'Gasca',
                'ApellidoMaterno' => 'Gutierrez',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'GAGL620810HGTSTR06',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1962-08-10',
                'FechaConstitucion' => null,
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:Si:Si:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 74,
                'ckAgente' => 1,
                'RFC' => 'BSM970519DU8',
                'Nombre' => '',
                'ApellidoPaterno' => '',
                'ApellidoMaterno' => '',
                'RazonSocial' => 'Banco Santander México S.A. Institución de Banca Múltiple Grupo Financiero Santander',
                'IDTipoPersona' => 2,
                'CURP' => '',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => null,
                'FechaConstitucion' => '1997-05-19',
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:Si:Si:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 88,
                'ckAgente' => 1,
                'RFC' => 'OAGG651113KV5',
                'Nombre' => 'Gildardo Héctor',
                'ApellidoPaterno' => 'Ordaz',
                'ApellidoMaterno' => 'García',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'OAGG651113HCLRRL04',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1965-11-13',
                'FechaConstitucion' => null,
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:Si:Si:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 89,
                'ckAgente' => 1,
                'RFC' => 'AERJ6407146T0',
                'Nombre' => 'Juan Carlos',
                'ApellidoPaterno' => 'Amézquita',
                'ApellidoMaterno' => 'Rodríguez',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'AERJ640714HGTMDN01',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1964-07-14',
                'FechaConstitucion' => null,
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:Si:Si:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 539,
                'ckAgente' => 1,
                'RFC' => 'LEFA6405136I9',
                'Nombre' => 'Antonio',
                'ApellidoPaterno' => 'León',
                'ApellidoMaterno' => 'Frich',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'LEFA640513HDFNRN03',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1964-05-13',
                'FechaConstitucion' => null,
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'No:Si:Si:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 635,
                'ckAgente' => 1,
                'RFC' => 'CURR591227G55',
                'Nombre' => 'Rebeca',
                'ApellidoPaterno' => 'Cruz',
                'ApellidoMaterno' => 'Rodríguez',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'CURR591227MGTRDB02',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1959-12-27',
                'FechaConstitucion' => null,
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'No:Si:Si:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 820,
                'ckAgente' => 1,
                'RFC' => 'MUPH590712AJA',
                'Nombre' => 'José Humberto',
                'ApellidoPaterno' => 'Muela',
                'ApellidoMaterno' => 'Pecero',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'MUPH590712HTSLCM05',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1959-07-12',
                'FechaConstitucion' => null,
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'No:Si:Si:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 821,
                'ckAgente' => 1,
                'RFC' => 'SFA050216RY2',
                'Nombre' => '',
                'ApellidoPaterno' => '',
                'ApellidoMaterno' => '',
                'RazonSocial' => 'Servicios y Financiamiento Agrícola S.A. de C.V. S.OF.O.M. E.N.R.',
                'IDTipoPersona' => 2,
                'CURP' => '',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => null,
                'FechaConstitucion' => '2005-02-16',
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:Si:Si:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 1019,
                'ckAgente' => 1,
                'RFC' => 'SAAC6205163B4',
                'Nombre' => 'Cecilia',
                'ApellidoPaterno' => 'Sánchez',
                'ApellidoMaterno' => 'Andrade',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'SAAC620516MDFNNC09',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1962-05-16',
                'FechaConstitucion' => null,
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:Si:Si:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 2346,
                'ckAgente' => 1,
                'RFC' => 'VICO52081096A',
                'Nombre' => 'Olegario',
                'ApellidoPaterno' => 'Vizcarra',
                'ApellidoMaterno' => 'Cortez',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'VICO520810HSPZRL07',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1952-08-10',
                'FechaConstitucion' => null,
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'No:Si:Si:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 2551,
                'ckAgente' => 1,
                'RFC' => 'CAGR6501282L2',
                'Nombre' => 'Rocio',
                'ApellidoPaterno' => 'Chávez',
                'ApellidoMaterno' => 'Guadarrama',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'CAGR650128MMCHDC01',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1965-01-28',
                'FechaConstitucion' => null,
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'No:Si:Si:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 2552,
                'ckAgente' => 1,
                'RFC' => 'EAS091009990',
                'Nombre' => '',
                'ApellidoPaterno' => '',
                'ApellidoMaterno' => '',
                'RazonSocial' => 'Elico Agente de Seguros y de Fianzas',
                'IDTipoPersona' => 2,
                'CURP' => '',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => null,
                'FechaConstitucion' => '2009-10-09',
                'FolioMercantil' => '30422*2',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:Si:Si:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 2733,
                'ckAgente' => 1,
                'RFC' => 'ALA091111MC6',
                'Nombre' => '',
                'ApellidoPaterno' => '',
                'ApellidoMaterno' => '',
                'RazonSocial' => 'AON Life, Agente de Seguros S.A de C.V.',
                'IDTipoPersona' => 2,
                'CURP' => '',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => null,
                'FechaConstitucion' => '2009-11-11',
                'FolioMercantil' => '176800',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:Si:No:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 2892,
                'ckAgente' => 1,
                'RFC' => 'VIRD860320IY0',
                'Nombre' => 'Diego',
                'ApellidoPaterno' => 'Villarreal',
                'ApellidoMaterno' => 'Ramírez',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'VIRD860320HNLLMG08',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1986-03-20',
                'FechaConstitucion' => null,
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'No:No:No:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 3104,
                'ckAgente' => 1,
                'RFC' => 'AACG690731G98',
                'Nombre' => 'Germán',
                'ApellidoPaterno' => 'Ayala',
                'ApellidoMaterno' => 'Chinchillas',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'AACG690731HSLYHR09',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1969-07-31',
                'FechaConstitucion' => null,
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'No:Si:Si:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 3348,
                'ckAgente' => 1,
                'RFC' => 'RORA600122GR0',
                'Nombre' => 'Agustín',
                'ApellidoPaterno' => 'Rodríguez',
                'ApellidoMaterno' => 'Romero',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'RORA600122HSRDMG02',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1960-01-22',
                'FechaConstitucion' => null,
                'FolioMercantil' => '0',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:No:No:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 3525,
                'ckAgente' => 1,
                'RFC' => 'GACR580404371',
                'Nombre' => 'Rigoberto Nazareth',
                'ApellidoPaterno' => 'García',
                'ApellidoMaterno' => 'Campaña',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'GACR580404HSLRMG13',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1958-04-04',
                'FechaConstitucion' => null,
                'FolioMercantil' => '0',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:No:No:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 3570,
                'ckAgente' => 1,
                'RFC' => 'MCA010316TD7',
                'Nombre' => '',
                'ApellidoPaterno' => '',
                'ApellidoMaterno' => '',
                'RazonSocial' => 'Murguía Consultores Agente de Seguros y de Fianzas, S.A. de C.V.',
                'IDTipoPersona' => 2,
                'CURP' => '',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => null,
                'FechaConstitucion' => '2001-03-16',
                'FolioMercantil' => '275333*',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:No:No:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 3843,
                'ckAgente' => 1,
                'RFC' => 'SSA170822EGA',
                'Nombre' => '',
                'ApellidoPaterno' => '',
                'ApellidoMaterno' => '',
                'RazonSocial' => 'Servicios Seguros 2000, Agente de Seguros, S.A. de C.V.',
                'IDTipoPersona' => 2,
                'CURP' => '',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => null,
                'FechaConstitucion' => '2017-08-22',
                'FolioMercantil' => '20180000119700NQ',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:No:No:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 3869,
                'ckAgente' => 1,
                'RFC' => 'SAFA600615Q18',
                'Nombre' => 'Alejandro',
                'ApellidoPaterno' => 'Sánchez De Ovando',
                'ApellidoMaterno' => 'Fonseca',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'SAFA600615HDFNNL06',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1960-06-15',
                'FechaConstitucion' => null,
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:No:No:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 4208,
                'ckAgente' => 1,
                'RFC' => 'CULA631029NF0',
                'Nombre' => 'Alejandro',
                'ApellidoPaterno' => 'Cuevas',
                'ApellidoMaterno' => 'Licea',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'CULA631029HGRVCL08',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1963-10-29',
                'FechaConstitucion' => null,
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:No:No:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 4316,
                'ckAgente' => 1,
                'RFC' => 'MAS110112IU1',
                'Nombre' => '',
                'ApellidoPaterno' => '',
                'ApellidoMaterno' => '',
                'RazonSocial' => 'Mi Agente de Seguros y de Fianzas, S.A. de C.V.',
                'IDTipoPersona' => 2,
                'CURP' => '',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => null,
                'FechaConstitucion' => '2011-03-23',
                'FolioMercantil' => '41089',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:Si:Si:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 4322,
                'ckAgente' => 1,
                'RFC' => 'SASJ680725MN1',
                'Nombre' => 'Joaquín',
                'ApellidoPaterno' => 'Sánchez',
                'ApellidoMaterno' => 'Sandoval',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'SASJ680725HDFNNQ04',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1968-07-25',
                'FechaConstitucion' => null,
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:No:No:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 4365,
                'ckAgente' => 1,
                'RFC' => 'MABA891024MK3',
                'Nombre' => 'Anel Lilian',
                'ApellidoPaterno' => 'Martínez',
                'ApellidoMaterno' => 'Biebrich',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'MABA891024MSRRBN01',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1989-10-24',
                'FechaConstitucion' => null,
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:Si:Si:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 4562,
                'ckAgente' => 1,
                'RFC' => 'GONC801129MHA',
                'Nombre' => 'Carlos Omar',
                'ApellidoPaterno' => 'Godínez',
                'ApellidoMaterno' => 'Nápoles',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'GONC801129HJCDPR09',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1980-11-29',
                'FechaConstitucion' => null,
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:Si:No:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 5249,
                'ckAgente' => 1,
                'RFC' => 'LULT651015K7A',
                'Nombre' => 'Teresa de Lourdes',
                'ApellidoPaterno' => 'Lugo',
                'ApellidoMaterno' => 'López',
                'RazonSocial' => '',
                'IDTipoPersona' => 1,
                'CURP' => 'LULT651015MCLGPR09',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => '1965-10-15',
                'FechaConstitucion' => null,
                'FolioMercantil' => '',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:No:No:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'IDCliente' => 6060,
                'ckAgente' => 1,
                'RFC' => 'ASA201228V47',
                'Nombre' => '',
                'ApellidoPaterno' => '',
                'ApellidoMaterno' => '',
                'RazonSocial' => 'Anter Seguros, Agente de seguros y de fianzas, S.A. de C.V.',
                'IDTipoPersona' => 2,
                'CURP' => '',
                'IDOcupacionGiro' => 1,
                'FechaNacimiento' => null,
                'FechaConstitucion' => '2020-12-28',
                'FolioMercantil' => 'N-2021002064',
                'CoincideEnListasNegras' => 0,
                'EsPPEActivo' => 0,
                'IDNacionalidad' => 1,
                'IDEstadoNacimiento' => null,
                'Activo' => 1,
                'Preguntas' => 'Si:Si:No:Si',
                'IngresosEstimados' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }

    public function down(): void
    {
        DB::table('tbClientes')->whereIn('RFC', [
            'GAGL620810S43',
            'BSM970519DU8',
            'OAGG651113KV5',
            'AERJ6407146T0',
            'LEFA6405136I9',
            'CURR591227G55',
            'MUPH590712AJA',
            'SFA050216RY2',
            'SAAC6205163B4',
            'VICO52081096A',
            'CAGR6501282L2',
            'EAS091009990',
            'ALA091111MC6',
            'VIRD860320IY0',
            'AACG690731G98',
            'RORA600122GR0',
            'GACR580404371',
            'MCA010316TD7',
            'SSA170822EGA',
            'SAFA600615Q18',
            'CULA631029NF0',
            'MAS110112IU1',
            'SASJ680725MN1',
            'MABA891024MK3',
            'GONC801129MHA',
            'LULT651015K7A',
            'ASA201228V47'
        ])->delete();
    }
};
